# Generated by Django 4.1.4 on 2023-01-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='update_f_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='update_l_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
