# Generated by Django 4.1.4 on 2023-01-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_update_f_name_register_update_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='option',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
